/**
 * Build Script
 * 建置腳本
 * Moves files to /dist folder for deployment.
 * 將檔案移動到 /dist 資料夾以進行部署。
 */
const fs = require('fs');
const path = require('path');

const destDir = path.join(__dirname, 'dist');

// Ensure dist directory exists
if (fs.existsSync(destDir)) {
    fs.rmSync(destDir, { recursive: true, force: true });
}
fs.mkdirSync(destDir);

// Helpers
function copyFile(file) {
    fs.copyFileSync(path.join(__dirname, file), path.join(destDir, file));
    console.log(`Copied ${file}`);
}

function copyDir(dir) {
    const src = path.join(__dirname, dir);
    const dest = path.join(destDir, dir);

    if (!fs.existsSync(dest)) fs.mkdirSync(dest);

    const files = fs.readdirSync(src);
    for (const file of files) {
        const srcFile = path.join(src, file);
        const destFile = path.join(dest, file);
        if (fs.statSync(srcFile).isDirectory()) {
            copyDir(path.join(dir, file));
        } else {
            fs.copyFileSync(srcFile, destFile);
        }
    }
    console.log(`Copied ${dir}/`);
}

// Execution
try {
    copyFile('index.html');
    // copyFile('css/style.css'); // No longer needed as we build to css/output.css
    copyDir('css'); // This will include output.css generated by tailwind
    copyDir('js');
    console.log('Build successful! Files copied to /dist');
} catch (e) {
    console.error('Build failed:', e);
    process.exit(1);
}
